### ISSUE TITLE
NEW ERROR

### ISSUE THREAD

**Issue by rodri2200** [Pymmdrza/EthereumMnemonicCrack#13]
Traceback (most recent call last):
  File "/home/runner/probarrrr/main.py", line 77, in <module>
    mmdrza()
  File "/home/runner/probarrrr/main.py", line 55, in mmdrza
    transaction(addr)) + '\n[/][gold1 on grey15]Addr: ' + '[white] ' + str(
  File "<string>", line 27, in transaction
IndexError: list index out of range

**Comment by Pymmdrza** [comment]
> Traceback (most recent call last): File "/home/runner/probarrrr/main.py", line 77, in mmdrza() File "/home/runner/probarrrr/main.py", line 55, in mmdrza transaction(addr)) + '\n[/][gold1 on grey15]Addr: ' + '[white] ' + str( File "", line 27, in transaction IndexError: list index out of range

---

### I do not see a problem. Please be careful in sending your problems. Don't open a case for your problem. We are not responsible for the problems of your personal system and the instructions for using the script have been sent. You should be a little more careful instead of posting such things.

---

You can see the current state of the script, which can be used without any errors: 

![Rec_Screen_MneEthOn_V4](https://github.com/Pymmdrza/EthereumMnemonicCrack/assets/95309780/d571cef8-55e8-4332-83a6-0ada8b080738)



Run in Replit [RUN NOW](https://replit.com/@Pymmdrza/EthereumMnemonic?v=1)
